### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by z3ntu** [nviennot/jd-core-java#23]
./gradlew assemble          
:compileJava UP-TO-DATE                                                         
:processResources UP-TO-DATE                                                    
:classes UP-TO-DATE                                                             
:getNativeLibs FAILED                                                           
                                                                                
FAILURE: Build failed with an exception.                                        
                                                                                
* What went wrong:                                                              
Execution failed for task ':getNativeLibs'.                                     
> A problem occurred starting process 'command 'hg''                            
                                                                                
* Try:                                                                          
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.                                                  
                                                                                
BUILD FAILED                                                                    
                                                                                
Total time: 2.129 secs

**Comment by z3ntu** [comment]
Okay, same as #20 ... mercurial helps... Please add that to the README.md!

**Comment by soumali** [comment]
Process 'command 'hg'' finished with non-zero exit value 255

gradlew.bat assemble

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:getNativeLibs
abort: error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
                                                                                                                                                                                                     :getNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:


Execution failed for task ':getNativeLibs'.
> Process 'command 'hg'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 13.079 secs

**Comment by z3ntu** [comment]
@soumali As it seems you are using Windows. It should be possible to install Mercurial for Windows, but the "hg" binary has to be in your path Variable (I think you can get it to work with Google & this message)

**Comment by soumali** [comment]
Thanks @z3ntu for your reply. I have installed the mercurial 3.8.3 exe and put it in my windows path. But still getting same exception

**Comment by z3ntu** [comment]
@soumali what happens if you type `hg` in cmd.exe? And please also post the content of your path variable.

**Comment by soumali** [comment]
@z3ntu Thanks for reverting back.
I was finally able to run hg. It was a proxy issue.
However, post downloading, I could see the native lib files are in the form of "jd.dll.d" & "jd.dll.i", against what I expected (in the form of jd.dll, libjd.so etc). Similar is the case for linux version native files. 

Are you able to compile the source of this project and generate output decompiled jars and classes?
